# Generated by Django 3.2.12 on 2022-02-26 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_comment_user_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comments',
        ),
    ]
