# Generated by Django 3.2.12 on 2022-03-08 09:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20220226_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment_given',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='comment',
        ),
        migrations.AddField(
            model_name='likes',
            name='post_like',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.post'),
            preserve_default=False,
        ),
    ]
