# Generated by Django 3.2.12 on 2022-03-09 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_rename_likes_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post_like',
            new_name='post',
        ),
    ]
